import { Faction } from '../../types/index.ts';
import { PoliticalInterests, RedLine } from './types.ts';
import { CRISIS_IDS } from './constants.ts';

export interface DetailedFaction extends Faction {
  wealth: number;          // 0 to 100
  politicalPower: number;  // 0 to 100
  interests: PoliticalInterests;
  redLines: RedLine[];
  tags: string[];
}

export const BASE_FACTIONS: DetailedFaction[] = [
  {
    id: 'faction_old_sich',
    name: 'Стара Січ',
    influence: 65,
    loyalty: 60,
    tension: 30,
    wealth: 45,
    politicalPower: 65,
    leaderName: 'Остап Коваленко',
    ideology: 'Свобода, військова традиція, давні права, козацьке самоврядування.',
    description: 'Низове козацтво, курінні отамани, ветерани степових баталій, оборонці давньої рівності та святості вольностей.',
    interests: {
      armyFunding: 40,
      taxation: -60,
      autonomy: 80,
      centralization: -80,
      landReform: -40,
      education: 20,
      tradeFreedom: 30,
      freedom: 90,
      stability: 40,
    },
    redLines: [
      {
        id: 'redline_old_sich_centralization',
        label: 'Недоторканність Козацької Автономії',
        metric: 'centralization',
        operator: '>',
        threshold: 70,
        consequenceDescription: 'Стара Січ сприймає надмірну централізацію як зраду козацьких вольностей та скликає бунтівну Старшинську Раду.',
        severity: 'crisis',
        crisisId: CRISIS_IDS.VOICE_OF_OLD_SICH,
      },
      {
        id: 'redline_old_sich_autonomy_drop',
        label: 'Захист Самоврядування Паланок',
        metric: 'autonomy_zaporizhzhia',
        operator: '<',
        threshold: 40,
        consequenceDescription: 'Зменшення автономії Запоріжжя нижче критичної межі викликає масове озброєння низовиків.',
        severity: 'opposition',
      },
    ],
    tags: ['козацтво', 'традиція', 'воля', 'хортиця'],
  },
  {
    id: 'faction_military_command',
    name: 'Військове Керівництво',
    influence: 75,
    loyalty: 65,
    tension: 40,
    wealth: 60,
    politicalPower: 80,
    leaderName: 'Генерал Данило Чайка',
    ideology: 'Державна безпека, непереможна регулярна армія, централізація, залізна дисципліна.',
    description: 'Генералітет та полковники Січі, які вважають дисципліну й артилерійський кулак єдиним гарантом виживання держави в оточенні імперій.',
    interests: {
      armyFunding: 90,
      taxation: 40,
      autonomy: -50,
      centralization: 75,
      landReform: 0,
      education: 30,
      tradeFreedom: 10,
      freedom: -20,
      stability: 70,
    },
    redLines: [
      {
        id: 'redline_military_strength_floor',
        label: 'Критична Межа Обороноздатності',
        metric: 'militaryStrength',
        operator: '<',
        threshold: 40,
        consequenceDescription: 'Падіння боєздатності армії нижче 40% змушує генералів виставити ультиматум Гетьману з вимогою повної мілітаризації.',
        severity: 'crisis',
        crisisId: CRISIS_IDS.MILITARY_COMMAND_ULTIMATUM,
      },
    ],
    tags: ['армія', 'генералітет', 'оборона', 'дисципліна'],
  },
  {
    id: 'faction_reformers',
    name: 'Реформатори',
    influence: 50,
    loyalty: 70,
    tension: 25,
    wealth: 55,
    politicalPower: 50,
    leaderName: 'Микола Берест',
    ideology: 'Інституції, освіта, модернізація, верховенство права та парові технології.',
    description: 'Молоді інженери, вчені Політехнічної Колегії, правознавці та організатори перших машинних заводів Січі.',
    interests: {
      armyFunding: 20,
      taxation: 30,
      autonomy: 10,
      centralization: 45,
      landReform: 60,
      education: 90,
      tradeFreedom: 75,
      freedom: 60,
      stability: 60,
    },
    redLines: [
      {
        id: 'redline_reformers_education_cut',
        label: 'Неприпустимість Згортання Освіти',
        metric: 'education',
        operator: '<',
        threshold: 25,
        consequenceDescription: 'Знищення вищих колегій та наукових лабораторій штовхає реформаторів у відкриту опозицію до Гетьмана.',
        severity: 'opposition',
      },
    ],
    tags: ['модерн', 'наука', 'інженерія', 'право'],
  },
  {
    id: 'faction_landed_aristocracy',
    name: 'Земська Аристократія',
    influence: 60,
    loyalty: 50,
    tension: 35,
    wealth: 85,
    politicalPower: 65,
    leaderName: 'Ян Корчак',
    ideology: 'Недоторканність приватної власності на землю, маєткові права, місцеве управління, шляхетські привілеї.',
    description: 'Великі землевласники та шляхтичі Правобережжя і Галичини, що володіють основними аграрними та соляними багатствами держави.',
    interests: {
      armyFunding: -20,
      taxation: -70,
      autonomy: 60,
      centralization: -60,
      landReform: -90,
      education: -10,
      tradeFreedom: 60,
      freedom: 30,
      stability: 75,
    },
    redLines: [
      {
        id: 'redline_aristocracy_land_reform',
        label: 'Заборона Експропріації Землі',
        metric: 'landReform',
        operator: '>',
        threshold: 50,
        consequenceDescription: 'Спроба примусового перерозподілу латифундій викликає збройний земський заколот у Галичині та Поділлі.',
        severity: 'crisis',
        crisisId: CRISIS_IDS.GALICIAN_LAND_REVOLT,
      },
    ],
    tags: ['земля', 'шляхта', 'власність', 'сеймики'],
  },
  {
    id: 'faction_communities',
    name: 'Громади',
    influence: 55,
    loyalty: 55,
    tension: 30,
    wealth: 50,
    politicalPower: 55,
    leaderName: 'Марія Левицька',
    ideology: 'Місцеві права, громадянська автономія, просвіта, свобода слова та цехова кооперація.',
    description: 'Міщани, ремісничі цехи, вчителі міських шкіл та селянські громади, що захищають низове самоврядування від тиску чиновників.',
    interests: {
      armyFunding: -30,
      taxation: -50,
      autonomy: 80,
      centralization: -70,
      landReform: 45,
      education: 75,
      tradeFreedom: 50,
      freedom: 85,
      stability: 50,
    },
    redLines: [
      {
        id: 'redline_communities_autonomy_strangle',
        label: 'Знищення Магістратського Самоврядування',
        metric: 'autonomy',
        operator: '<',
        threshold: 30,
        consequenceDescription: 'Ліквідація місцевих виборів та придушення цехів провокує загальний міський страйк та податковий бунт.',
        severity: 'crisis',
        crisisId: CRISIS_IDS.COMMUNITIES_TAX_STRIKE,
      },
    ],
    tags: ['громади', 'самоврядування', 'цехи', 'культура'],
  },
  {
    id: 'faction_merchants',
    name: 'Купецтво',
    influence: 50,
    loyalty: 60,
    tension: 25,
    wealth: 90,
    politicalPower: 55,
    leaderName: 'Лев Острозький',
    ideology: 'Вільна торгівля, стабільність фінансів, низькі митні бар’єри, розвиток портів та судноплавства.',
    description: 'Купці чорноморських портів, власники дніпровських барж, торговці сіллю та залізом, що фінансують державні кредити.',
    interests: {
      armyFunding: 30,
      taxation: -60,
      autonomy: 20,
      centralization: 20,
      landReform: 20,
      education: 40,
      tradeFreedom: 90,
      freedom: 50,
      stability: 85,
    },
    redLines: [
      {
        id: 'redline_merchants_prosperity_collapse',
        label: 'Падіння Торговельного Обороту',
        metric: 'prosperity',
        operator: '<',
        threshold: 30,
        consequenceDescription: 'Економічний колапс та свавілля митників змушують купецькі гільдії припинити кредитування гетьманської скарбниці.',
        severity: 'opposition',
      },
    ],
    tags: ['торгівля', 'капітал', 'порти', 'золото'],
  },
  {
    id: 'faction_intellectuals',
    name: 'Інтелектуали',
    influence: 45,
    loyalty: 65,
    tension: 20,
    wealth: 35,
    politicalPower: 45,
    leaderName: 'Професор Григорій Савич',
    ideology: 'Освіта народу, наука, культура, філософська думка, свобода слова та історична пам’ять.',
    description: 'Викладачі Києво-Могилянської та Львівської академій, літератори, лікарі та видавці перших часописів Січі.',
    interests: {
      armyFunding: -40,
      taxation: 10,
      autonomy: 50,
      centralization: -20,
      landReform: 50,
      education: 95,
      tradeFreedom: 40,
      freedom: 85,
      stability: 45,
    },
    redLines: [
      {
        id: 'redline_intellectuals_censorship',
        label: 'Запровадження Тотальної Цензури',
        metric: 'freedom',
        operator: '<',
        threshold: 30,
        consequenceDescription: 'Утиски академічних свобод та закриття друкарень викликають відтік умів та бойкот гетьманських указів.',
        severity: 'opposition',
      },
    ],
    tags: ['академія', 'наука', 'філософія', 'слово'],
  },
];
