import { GameState } from './types.ts';
import { BASE_FACTIONS } from '../politics/factionsData.ts';
import { BASE_INSTITUTIONS } from '../politics/institutionsData.ts';
import { BASE_REGIONS } from '../politics/regionsData.ts';
import { PoliticalRelationship } from '../politics/types.ts';
import { EconomyState } from '../economy/types.ts';
import { MilitaryState } from '../military/types.ts';

export const CURRENT_STATE_VERSION = 7;

export function createInitialGameState(rulerName = 'Ярослав Нескорений'): GameState {
  const gameId = 'sich_' + Date.now() + '_' + Math.random().toString(36).substring(2, 7);

  const initialRelationships: PoliticalRelationship[] = [
    {
      id: 'rel_hetman_chaika',
      sourceId: 'hetman',
      targetId: 'general_chaika',
      trust: 5,
      respect: 12,
      fear: 6,
      loyalty: 8,
      tension: 30,
      history: [{ year: 1848, delta: 0, reason: 'Присяга при інтронізації' }],
    },
    {
      id: 'rel_hetman_levytska',
      sourceId: 'hetman',
      targetId: 'maria_levytska',
      trust: 4,
      respect: 10,
      fear: 0,
      loyalty: 6,
      tension: 20,
      history: [{ year: 1848, delta: 0, reason: 'Петиція просвітників Києва' }],
    },
    {
      id: 'rel_hetman_kovalenko',
      sourceId: 'hetman',
      targetId: 'ostap_kovalenko',
      trust: 8,
      respect: 10,
      fear: 1,
      loyalty: 12,
      tension: 25,
      history: [{ year: 1848, delta: 0, reason: 'Вручення клейнодів Хортиці' }],
    },
    {
      id: 'rel_hetman_korchak',
      sourceId: 'hetman',
      targetId: 'jan_korchak',
      trust: 2,
      respect: 6,
      fear: 3,
      loyalty: 2,
      tension: 35,
      history: [{ year: 1848, delta: 0, reason: 'Діалог зі шляхетським сеймиком' }],
    },
    {
      id: 'rel_hetman_berest',
      sourceId: 'hetman',
      targetId: 'mykola_berest',
      trust: 6,
      respect: 9,
      fear: 0,
      loyalty: 8,
      tension: 15,
      history: [{ year: 1848, delta: 0, reason: 'Подання інженерного проєкту' }],
    },
  ];

  return {
    version: CURRENT_STATE_VERSION,

    identity: {
      gameId,
      rulerName,
      rulerTitle: 'Гетьман Імперії Січ',
      year: 1848,
    },

    empire: {
      stability: 65,
      treasury: 50,
      militaryStrength: 60,
      unity: 58,
      prosperity: 55,
    },

    // Stage 5 Material Machine Core
    economy: {
      treasury: 50,
      income: 44,
      expenses: 38,
      taxRevenue: 20,
      tradeRevenue: 12,
      resourceRevenue: 7,
      customsRevenue: 5,
      extraordinaryRevenue: 0,
      militaryExpenses: 16,
      administrativeExpenses: 11,
      infrastructureExpenses: 7,
      educationExpenses: 4,
      emergencyExpenses: 0,
      debt: 10,
      debtInterest: 5, // 5% annual
      creditLimit: 60,
      inflation: 3.5,
      economicGrowth: 2.4,
      publicProsperity: 55,
      taxBurden: 38,
      taxEfficiency: 68,
      taxPolicy: 'moderate',
      trade: {
        tradeVolume: 58,
        tradeFreedom: 55,
        portEfficiency: 62,
        merchantInfluence: 55,
        customsRevenue: 5,
        tariffsRate: 25,
      },
      educationLevel: 50,
      educationInvestment: 4,
      humanCapital: 52,
      investments: [],
      stateProjects: [],
      crises: [],
      trends: {
        treasury: 6,
        treasuryReason: 'Початковий стабільний профіцит скарбниці (+6 млн)',
        prosperity: 0,
        prosperityReason: 'Рівновага між податковим тиском та торгівлею',
        debt: 0,
        debtReason: 'Помірний борг у межах безпечної норми',
        growth: 2.4,
        growthReason: 'Торгівля зерном та чумацькі валки',
      },
    },

    military: {
      strength: 60,
      readiness: 70,
      morale: 68,
      manpower: 65,
      equipment: 58,
      logistics: 56,
      militaryExpenses: 16,
      officerLoyalty: 68,
      veteranInfluence: 72,
      trends: {
        strength: 0,
        strengthReason: 'Кадровий реєстр регулярних і козацьких полків',
        readiness: 0,
        readinessReason: 'Штатний рівень бойової готовності',
        morale: 0,
        moraleReason: 'Піднесення після обрання нового Гетьмана',
        logistics: 0,
        logisticsReason: 'Транспортні обози функціонують у межах норми',
      },
    },

    // Stage 4 Political Machine additions
    politicalCapital: 55,
    legitimacy: {
      tradition: 70,
      law: 60,
      success: 65,
      popularSupport: 58,
      eliteSupport: 55,
      militarySupport: 72,
    },
    institutions: BASE_INSTITUTIONS,
    promises: [],
    crises: [],
    politicalRelationships: initialRelationships,
    activeProposal: null,

    // Regions: Core 4 MVP regions + additional industrial belt
    regions: [
      ...BASE_REGIONS,
      {
        id: 'region_black_sea',
        name: 'Чорноморський Рубіж',
        population: '1.2M моряків та портовиків',
        wealth: 65,
        stability: 60,
        loyalty: 60,
        prosperity: 65,
        security: 65,
        unrest: 25,
        tension: 25,
        autonomy: 40,
        garrisonStrength: 65,
        taxContribution: 16,
        tradeContribution: 85,
        cultureTags: ['верфі', 'морська_торгівля', 'козацькі_чайки'],
        dominantFactions: ['faction_merchants', 'faction_military_command'],
        infrastructure: {
          roads: 55,
          ports: 80,
          railways: 0,
          administration: 60,
        },
        economicPotential: {
          trade: 90,
          tax: 60,
          resources: 50,
          industry: 65,
        },
        description: 'Одеські та миколаївські верфі, форпости та брама до Середземноморської торгівлі.',
      },
      {
        id: 'region_sivershchyna',
        name: 'Сіверський Промисловий Пояс',
        population: '2.1M гірників та майстрів',
        wealth: 50,
        stability: 65,
        loyalty: 65,
        prosperity: 50,
        security: 55,
        unrest: 20,
        tension: 20,
        autonomy: 35,
        garrisonStrength: 55,
        taxContribution: 18,
        tradeContribution: 55,
        cultureTags: ['залізорудні_копальні', 'парові_майстерні', 'доменні_печі'],
        dominantFactions: ['faction_reformers', 'faction_communities'],
        infrastructure: {
          roads: 50,
          ports: 15,
          railways: 0,
          administration: 55,
        },
        economicPotential: {
          trade: 55,
          tax: 65,
          resources: 85,
          industry: 80,
        },
        description: 'Залізорудні копальні, парові майстерні, доменні печі та лісові мануфактури.',
      },
    ],

    // 7 Base Factions
    factions: BASE_FACTIONS,

    characters: [
      {
        id: 'general_chaika',
        name: 'Данило Чайка',
        role: 'Генерал Кордонних Корпусів Січі',
        factionId: 'faction_military_command',
        regionId: 'region_sich_core',
        influence: 80,
        trust: 5,
        respect: 12,
        fear: 6,
        loyalty: 8,
        tags: ['армія', 'ветеран', 'дисципліна'],
        interests: ['armyFunding', 'centralization', 'security'],
        bio: 'Загартований у боях командувач, символ степової військової потуги. Вимагає сильного бюджету для армії і не вірить пустим балачкам дипломатів.',
        interactionHistory: [
          {
            year: 1848,
            note: 'Приніс присягу новому Гетьману від імені Прикордонних Корпусів.',
          },
        ],
      },
      {
        id: 'maria_levytska',
        name: 'Марія Левицька',
        role: 'Представниця київської інтелігенції та просвітницьких кіл',
        factionId: 'faction_communities',
        regionId: 'region_podillia',
        influence: 60,
        trust: 4,
        respect: 10,
        fear: 0,
        loyalty: 6,
        tags: ['просвіта', 'громади', 'культура'],
        interests: ['education', 'autonomy', 'freedom'],
        bio: 'Засновниця таємних шкіл та видавництв у Києві. Переконана, що без освіти народу та міцних громад будь-яка імперія розпадеться зсередини.',
        interactionHistory: [
          {
            year: 1848,
            note: 'Звернулася з петицією про підтримку українського друкарства та міських шкіл.',
          },
        ],
      },
      {
        id: 'jan_korchak',
        name: 'Ян Корчак',
        role: 'Галицький землевласник, представник шляхетських сеймиків',
        factionId: 'faction_landed_aristocracy',
        regionId: 'region_galicia',
        influence: 70,
        trust: 2,
        respect: 6,
        fear: 3,
        loyalty: 2,
        tags: ['земля', 'автономія', 'шляхта'],
        interests: ['landReform', 'autonomy', 'tradeFreedom'],
        bio: 'Впливовий магнат із Галичини. Обстоює інтереси аграрних експортерів та вимагає від гетьманського уряду поваги до місцевих прав.',
        interactionHistory: [
          {
            year: 1848,
            note: 'Висловив підтримку союзу з Січчю за умови збереження земських судів.',
          },
        ],
      },
      {
        id: 'ostap_kovalenko',
        name: 'Остап Коваленко',
        role: 'Курінний отаман Низового Козацтва Старої Січі',
        factionId: 'faction_old_sich',
        regionId: 'region_sich_core',
        influence: 75,
        trust: 8,
        respect: 10,
        fear: 1,
        loyalty: 12,
        tags: ['козацтво', 'традиція', 'воля'],
        interests: ['autonomy', 'freedom', 'armyFunding'],
        bio: 'Хранитель козацьких звичаїв Хортиці. Вважає, що справжня Січ — це братерство і воля, а не бюрократичний імперський апарат.',
        interactionHistory: [
          {
            year: 1848,
            note: 'Особисто вручив новообраному Гетьману клейноди правління.',
          },
        ],
      },
      {
        id: 'mykola_berest',
        name: 'Микола Берест',
        role: 'Молодий інженер-реформатор, секретар Технічної Колегії',
        factionId: 'faction_reformers',
        regionId: 'region_sivershchyna',
        influence: 50,
        trust: 6,
        respect: 9,
        fear: 0,
        loyalty: 8,
        tags: ['реформа', 'наука', 'інженерія'],
        interests: ['education', 'tradeFreedom', 'centralization'],
        bio: 'Випускник політехніки, ентузіаст парових технологій, будівництва залізниць та сучасної нарізної металургії.',
        interactionHistory: [
          {
            year: 1848,
            note: 'Презентував план індустріалізації дніпровських порогів.',
          },
        ],
      },
      {
        id: 'rector_ostrozka',
        name: 'Софія Острозька',
        role: 'Ректорка Політехнічної Академії та Ливарної Колегії',
        factionId: 'faction_reformers',
        regionId: 'region_podillia',
        influence: 58,
        trust: 8,
        respect: 12,
        fear: 0,
        loyalty: 10,
        tags: ['наука', 'інновація', 'ливарні'],
        interests: ['education', 'reform', 'science'],
        bio: 'Провідна вчена та організаторка інженерних шкіл Січі. Вважає науку та точну металургію головною запорукою суверенітету держави у XIX столітті.',
        interactionHistory: [
          {
            year: 1848,
            note: 'Очолила розробку перших нарізних гармат для Січового Арсеналу.',
          },
        ],
      },
      {
        id: 'lev_ostrozkyi',
        name: 'Лев Острозький',
        role: 'Голова Купецької Гільдії Чорноморських Портів',
        factionId: 'faction_merchants',
        regionId: 'region_black_sea',
        influence: 55,
        trust: 5,
        respect: 8,
        fear: 0,
        loyalty: 6,
        tags: ['купецтво', 'порти', 'золото'],
        interests: ['tradeFreedom', 'taxation', 'stability'],
        bio: 'Організатор чорноморського торговельного пароплавства, кредитор арсеналів та захисник низьких мит.',
        interactionHistory: [
          {
            year: 1848,
            note: 'Запропонував відкрити безмитні склади в Одеському порту.',
          },
        ],
      },
      {
        id: 'hryhorii_savych',
        name: 'Професор Григорій Савич',
        role: 'Декан Філософського Факультету Києво-Могилянської Академії',
        factionId: 'faction_intellectuals',
        regionId: 'region_podillia',
        influence: 48,
        trust: 7,
        respect: 11,
        fear: 0,
        loyalty: 9,
        tags: ['академія', 'філософія', 'слово'],
        interests: ['education', 'freedom', 'autonomy'],
        bio: 'Провідний гуманіст та мислитель, автор праць про природне право та соборний устрій козацької республіки.',
        interactionHistory: [
          {
            year: 1848,
            note: 'Підніс Гетьману памфлет про права людини і громадянина Січі.',
          },
        ],
      },
    ],

    relationships: {
      general_chaika: 20,
      maria_levytska: 15,
      jan_korchak: 5,
      ostap_kovalenko: 25,
      mykola_berest: 18,
      rector_ostrozka: 15,
      lev_ostrozkyi: 12,
      hryhorii_savych: 14,
    },

    decisions: [],
    consequences: [],
    scheduledConsequences: [],

    history: [
      {
        id: 'hist_1848_election',
        year: 1848,
        timestamp: Date.now(),
        type: 'COUNCIL_DECISION',
        title: 'Велика Рада 1848 року: Обрання нового Гетьмана',
        description: `У буремний рік "Весни Народів" Велика Січова Рада вручила клейноди правління новому володарю — ${rulerName}. Попереду виклики перебудови та захисту рубежів.`,
        importance: 'critical',
        tags: ['велика_рада', 'інтронізація', '1848'],
        category: 'decision',
      },
    ],

    psychology: [],

    // Fundamental Dual Tensions (Requirements 15 & 16)
    tensions: {
      tension_freedom_order: 50,
      tension_autonomy_centralization: 45,
      tension_tradition_reform: 50,
      tension_might_prosperity: 55,
      tension_unity_diversity: 50,
      tension_expansion_sustainability: 40,
    },

    tensionRecords: [
      {
        id: 'tension_freedom_order',
        poleA: 'СВОБОДА',
        poleB: 'ПОРЯДОК',
        value: 50,
        source: 'Устрій Січі',
        history: [{ year: 1848, delta: 0, reason: 'Початкова рівновага' }],
      },
      {
        id: 'tension_autonomy_centralization',
        poleA: 'АВТОНОМІЯ',
        poleB: 'ЦЕНТРАЛІЗАЦІЯ',
        value: 45,
        source: 'Відносини з воєводствами',
        history: [{ year: 1848, delta: 0, reason: 'Початкова рівновага' }],
      },
      {
        id: 'tension_tradition_reform',
        poleA: 'ТРАДИЦІЯ',
        poleB: 'РЕФОРМА',
        value: 50,
        source: 'Військово-соціальний устрій',
        history: [{ year: 1848, delta: 0, reason: 'Початкова рівновага' }],
      },
      {
        id: 'tension_might_prosperity',
        poleA: 'СИЛА',
        poleB: 'ДОБРОБУТ',
        value: 55,
        source: 'Державний бюджет',
        history: [{ year: 1848, delta: 0, reason: 'Початкова рівновага' }],
      },
      {
        id: 'tension_unity_diversity',
        poleA: 'ЄДНІСТЬ',
        poleB: 'РІЗНОМАНІТТЯ',
        value: 50,
        source: 'Культурні та станові пласти',
        history: [{ year: 1848, delta: 0, reason: 'Початкова рівновага' }],
      },
      {
        id: 'tension_expansion_sustainability',
        poleA: 'РОЗШИРЕННЯ',
        poleB: 'СТІЙКІСТЬ',
        value: 40,
        source: 'Геополітична стратегія',
        history: [{ year: 1848, delta: 0, reason: 'Початкова рівновага' }],
      },
    ],

    discoveries: [
      'Хортицька чавуноливарна формула 1840-х',
      'Статут Військової ради Січі',
    ],

    flags: {
      army_budget_boosted: false,
      army_budget_cut: false,
      military_reform_instituted: false,
    },

    reputationTags: [],
    memoryTags: [],
    reputationSignals: [],
    narrativeMirrors: [],

    eventQueue: [],

    currentScenarioId: 'scenario_first_council',
    completedScenarioIds: [],
    availableScenarioIds: ['scenario_first_council'],

    yearProgress: {
      year: 1848,
      completedScenarioIds: [],
      resolvedScenarioCount: 0,
      totalRequiredScenarios: 3,
      yearStartMetrics: {
        stability: 65,
        treasury: 50,
        militaryStrength: 60,
        unity: 58,
        prosperity: 55,
      },
    },
    yearSummary: null,

    unlockedScenarioIds: ['scenario_first_council'],
    lockedScenarioIds: [],

    archetypeProfile: {
      archetype: 'ОХОРОНЕЦЬ',
      archetypeCode: 'GUARDIAN',
      summaryQuote: '«Не ми цей лад починали — не нам його й ламати. Рубежі повинні стояти твердо.»',
      evidence: ['Обрання на Великій Січовій Раді 1848 року'],
      strength: 'Спадкове козацьке право та довіра Старшинської Ради',
      shadow: 'Ризик потрапити під надмірний вплив мілітарної старшини',
      contradiction: 'Пошук рівноваги між становою вольницею та потребою сильної оборони рубежів',
      transformations: [],
      unresolvedQuestion: 'Чи можна захистити віковічні вольності, не розколовши державу перед зовнішньою загрозою?',
      keyDecisions: ['1848 р. — Обрання нового Гетьмана на Хортиці'],
      calculatedAtYear: 1848,
      dominantTendencies: [],
      secondaryTendencies: [],
      tensionsAndContradictions: [],
      recognizedStrengths: ['Спадкове козацьке право', 'Довіра Старшинської Ради'],
      shadowRisks: ['Ризик потрапити під вплив мілітарної фракції'],
      historicalPrecedents: ['Богдан Хмельницький (1648)', 'Іван Мазепа (1700)'],
      tentativeArchetypeTitle: 'ОХОРОНЕЦЬ',
    },

    // Stage 6 Psychological Ascension Core
    behaviorPatterns: [],
    contradictions: [],
    psychologicalTensions: [],
    reflections: [],
    insights: [],
    stressTests: [],
    transformations: [],
    ascensionStage: 'EXPERIENCE',

    lastSavedTimestamp: Date.now(),
  };
}
